import React from 'react'
import './global.css'
import Header from '@/components/Header'

interface RootLayoutProps {
  children: React.ReactNode
}

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="ko-KR">
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  )
}
